In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

In [3]:
PROJECT_ROOT = Path.cwd().parent
RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

DATA_FILE = "WA_Fn-UseC_-Telco-Customer-Churn.csv"
DATA_PATH = RAW_DIR / DATA_FILE

DATA_PATH

WindowsPath('C:/Users/shrut/OneDrive/Desktop/customer-churn-platform/data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [4]:
df = pd.read_csv(DATA_PATH)

df.shape

(7043, 21)

In [5]:
df["TotalCharges"].head(10)

0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
5      820.5
6     1949.4
7      301.9
8    3046.05
9    3487.95
Name: TotalCharges, dtype: object

In [6]:
df["TotalCharges"] = df["TotalCharges"].replace(" ", np.nan)
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"])

In [7]:
df["TotalCharges"].isna().sum()

11

In [8]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [9]:
df["TotalCharges"].isna().sum()

0

In [10]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [11]:
yes_no_cols = []

for col in df.columns:
    if set(df[col].dropna().unique()).issubset({"Yes", "No"}):
        yes_no_cols.append(col)

yes_no_cols

['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']

In [12]:
for col in yes_no_cols:
    df[col] = df[col].map({"Yes": 1, "No": 0})

In [13]:
df[yes_no_cols].head()

   Partner  Dependents  PhoneService  PaperlessBilling  Churn
0        1           0             0                 1      0
1        0           0             1                 0      0
2        0           0             1                 1      1
3        0           0             0                 0      0
4        0           0             1                 1      1

In [14]:
df.replace(
    {
        "No internet service": "No",
        "No phone service": "No"
    },
    inplace=True
)

In [15]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [16]:
df.duplicated().sum()

0

In [17]:
df.shape
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,1,0,1,0,No,DSL,No,...,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,0,0,34,1,No,DSL,Yes,...,Yes,No,No,No,One year,0,Mailed check,56.95,1889.50,0
2,3668-QPYBK,Male,0,0,0,2,1,No,DSL,Yes,...,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,0,0,45,0,No,DSL,Yes,...,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,0,0,2,1,No,Fiber optic,No,...,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1

In [18]:
clean_path = PROCESSED_DIR / "cleaned_churn_data.csv"
df.to_csv(clean_path, index=False)

clean_path

WindowsPath('C:/Users/shrut/OneDrive/Desktop/customer-churn-platform/data/processed/cleaned_churn_data.csv')

Hidden missing values in TotalCharges were detected and converted to numeric format. Missing values corresponded to new customers with zero tenure and were handled accordingly. Categorical values were standardized and validated to ensure analysis consistency.